version: '3'

services:
  code-rookie.cli-alpine:
    build:
      context: .
      dockerfile: dockerfile.cli-alpine-test
  code-rookie.cli-debian:
    build:
      context: .
      dockerfile: dockerfile.cli-debian-test
  code-rookie.api:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "3000:3000"
    
